packages:
  - .
  - apps/*
  - packages/*
  - packages/contracts/*
  - packages/repositories/*

nodeLinker: hoisted
blockExoticSubdeps: false
allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  isolated-vm: true
minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.3'
  - vue-tsc@3.3.3
  - better-sqlite3@12.10.1
overrides:
  hono: 4.12.30
  viem: 2.55.1
